services:
  # service to get intership data
  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GITHUB_API_URL: ${GITHUB_API_URL}
      GITHUB_API_TOKEN: ${GITHUB_API_TOKEN}
    depends_on:
      - postgres

  # frontend service
  frontend:
    build: 
      context: ./frontend
    ports:
      - "8080:5173"
    environment:
      VITE_GA_TRACKING_ID: ${VITE_GA_TRACKING_ID}
    depends_on:
      - backend

  # postgres service for backend
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: