services:
  # service to get intership data
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - "./backend:/go/src/backend"
    ports:
      - "8000:8000"

  # frontend service
  frontend:
    build: 
      context: ./frontend
    volumes:
      - "./frontend/src:/frontend/src"
    ports:
      - "8080:5173"
    depends_on:
      - backend